[projects]

  [projects.default]
  contents = [
    "preface",
    "why_julia",
    "julia_101",
    "dataframes_overview",
    "plots_overview"
  ]
  port = 8004
  output_filename = "juliadatascience"
